# Project info
site_name: IBM Cloud for VMware Solutions
site_description: IBM Cloud for VMware Solutions Level 3 Demonstration Guide
site_author: Andrew R. Jones (andrewj@us.ibm.com) & Chris Bienko (cdbienko@us.ibm.com)
copyright: Copyright &copy; 2022 IBM

# Repository
repo_name:  IBM/SalesEnablement-VMware-L3

#repo_url: https://github.com/IBM/SalesEnablement-VMware-L3
#edit_uri: edit/master/docs
docs_dir: docs


nav:
  - 'Welcome': 'index.md'
  - 'VMware Solutions Shared (OPTIONAL)':
    - 'Introduction': 'Shared/Introduction.md'
    - 'Provisioning': 'Shared/Provisioning.md'
    - 'Managing': 'Shared/Managing.md'
    - 'Hands On Access': 'Shared/HandsOn.md'
  - 'VMware as a Service':
    - 'Introduction': 'VMWaaS/Introduction.md'
    - 'Provisioning': 'VMWaaS/Provisioning.md'
    - 'Managing': 
      - 'Overview': 'VMWaaS/Managing/ManagingIntro.md'
      - 'Managing a VMaaS instance using the IBM Cloud Portal': 'VMWaaS/Managing/ManagingSite.md'
      - 'Managing a VDC using vCloud Director': 'VMWaaS/Managing/ManagingVDC.md'
      - 'The client demonstration': 'VMWaaS/PuttingItAllTogether.md'
  - 'VMware Solutions Dedicated':
    - 'Introduction': 'Dedicated/Introduction.md'
    - 'Provisioning': 'Dedicated/Provisioning.md'
    - 'Managing': 'Dedicated/Managing.md'
  - 'Next Steps': 'NextSteps.md'

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
    - mkdocs-video
    - macros
    - search

markdown_extensions:
  - sane_lists
  - pymdownx.details
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - attr_list

extra:
  generator: false
  gitRepo: "https://github.com/IBM/SalesEnablement-VMware-L3"
  learningplan:
    name: "IBM Cloud for VMware Solutions Level 3"
  level2learningplan:
    name: "IBM Cloud for VMware Solutions Sales Foundation"
    YLurl: "https://yourlearning.ibm.com/activity/PLAN-9B285157EA97"
    BPurl: "https://learn.ibm.com/course/view.php?id=11142"
  offering:
    name: "IBM Cloud for VMware Solutions"
  guide:
    name: "IBM Cloud for VMware Solutions - Level 3 Demonstration Guide"
    url: "https://ibm.github.io/SalesEnablement-VMware-L3/"
  itz:
    account: "2326338 - ITZ-VMWARE"
    collection: ""
    environment: ""
    resourceGroup: "Enablement-L3"
    dedicated:
      instanceName: "vcs-l3"
      clusterName: "vcs-dv-consolidated"
    vmaas:
      siteName: "se-le-site"
      pvdc: "se-l3-provider"
      cluster1: "se-l3-cluster1"
      vdc1: "se-l3-development"
      vdc2: "se-l3-production"
